"use client";

import type { Metadata } from "next";
import "../../styles/globals.scss";
import { ClerkProvider, SignedIn, SignedOut } from "@clerk/nextjs";
import { usePathname } from "next/navigation";
import { checkIsPublicRoute } from "@/utils/check-route";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { UserProvider } from "@/contexts/UserContext";
import { Suspense } from "react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // Pegar o pathname atual da URL
  const path = usePathname();

  // Validação de Rota Púlbica e Privada
  const isPublic = checkIsPublicRoute(path);

  const metadata: Metadata = {
    title: "BadumTS",
    description: "Generated by create next",
  };

  return (
    <ClerkProvider>
      <html lang="pt-br">
        <Suspense>
          <body className="selection:bg-blue-200 selection:text-white">
            {isPublic && (
              <>
                <SignedIn>
                  <UserProvider>
                    <div className="main">
                      <div className="gradient" />
                    </div>
                    <div className="z-10 relative">
                      <Navbar />
                      <main className="min-h-[82vh] w-full sm:pt-[150px] pt-[125px] flex flex-col items-center">
                        {children}
                      </main>
                      <Footer />
                    </div>
                  </UserProvider>
                </SignedIn>
                <SignedOut>
                  <div className="main">
                    <div className="gradient" />
                  </div>
                  <div className="z-10 relative">
                    <Header />
                    <main className="min-h-[82vh] w-full sm:pt-[150px] pt-[125px] flex flex-col items-center">
                      {children}
                    </main>
                    <Footer />
                  </div>
                </SignedOut>
              </>
            )}

            {!isPublic && (
              <SignedIn>
                <UserProvider>
                  <Navbar />
                  <main className="min-h-[82vh] w-full sm:pt-[85px] flex flex-col items-center">
                    {children}
                  </main>
                  <Footer />
                </UserProvider>
              </SignedIn>
            )}
          </body>
        </Suspense>
      </html>
    </ClerkProvider>
  );
}
